[package]
name = "day7_1"
version = "0.1.0"
authors = ["David Schultz <davids24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { git = "https://github.com/rust-itertools/itertools" }