[package]
name = "day16_1"
version = "0.1.0"
authors = ["David Schultz <davids24@gmail.com>"]
edition = "2018"
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]